---
title: "rnaSEQ_data_simulation"
author: "SAAD George Alehandro"
date: "11/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Let's suppose 10 samples: 5 healthy salmons - 5 infected by a virus
12 genes: 6 showing differences - 6 indifferent

```{r}
simulate_indifferent <- function(){
  rnorm(10, 5, 1)
}

simulate_different_upregulated <- function(){
  c(rnorm(5, 5, 1), rnorm(2,30,10), rnorm(3,80,10))
}

simulate_different_downregulated <- function(){
  c(rnorm(5,40,10), rnorm(5, 5, 1))
}
```



```{r}
df <- data.frame(row.names = c("H1","H2","H3","H4","H5","S1", "S2", "S3", "S4", "S5"))
#Simulating indifferent genes
df$TE21 <-simulate_indifferent()
df$AKN2 <-simulate_indifferent()
df$CTF3 <-simulate_indifferent()
df$GAN <-simulate_indifferent()
df$ZAM3 <-simulate_indifferent()
#Simulating upregulated genes in the case of virus
df$NAE1 <-simulate_different_upregulated()
df$NEDD8 <-simulate_different_upregulated()
df$COM9 <-simulate_different_upregulated()
df$ADD3 <-simulate_different_upregulated()
df$ERTS <-simulate_different_upregulated()
#Simulating downregulated genes in the case of virus
df$SADE <-simulate_different_downregulated()
df$FFDC <-simulate_different_downregulated()
df$LOF3 <-simulate_different_downregulated()
df$CSF <-simulate_different_downregulated()
df$IRK <-simulate_different_downregulated()
head(df)
```

```{r}
library("NMF")
```

```{r}
nmf_result <- nmf(df, rank = 3)
```

```{r}
fitted_result <- fitted(nmf_result)
```

```{r}
w<-basis(nmf_result) 
dim(w) #getmatrixH
h<-coef(nmf_result)
```

```{r}
s<-featureScore(nmf_result) 
summary(s)
s<-extractFeatures(nmf_result) 
str(s)
```

```{r}
consensusmap(nmf_result, annCol = df, labCol=NA,labRow=colnames(df))
```


